name: chatjbd
channels:
  - defaults
dependencies:
  - python==3.8.10
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
    - torch
    - torchtext
    - notebook
    - numpy
    - spacy
    - transformers
    - pandas
    - sklearn

